###
POST http://localhost:9001/api/v1/users
Content-Type: application/json

{
    "username": "Anil",
    "email": "anil@gmail.com",
    "password": "hello"
}

###

POST http://localhost:9001/api/v1/users/login
Content-Type:  application/json

{
    "email": "a@gmail.com",
    "password": "123"
}


###
POST http://localhost:9001/api/v1/transactions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzMyYzhjNGFiYTE2ZWI0MWJhNTRmM2YiLCJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzMxMzgzODQ0LCJleHAiOjE3MzE0NzAyNDR9.oMvJKvOY-oy2jiVs_XOJFriFrODvW3nYxf_fmsQ-c-w

{
    "type": "credit",
    "amount": "12300.00",
    "description": "Purchase of equipment",
    "date": "2024-11-11T09:00:00Z"
}


###
GET http://localhost:9001/api/v1/transactions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzMyYzhjNGFiYTE2ZWI0MWJhNTRmM2YiLCJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzMxMzgzODQ0LCJleHAiOjE3MzE0NzAyNDR9.oMvJKvOY-oy2jiVs_XOJFriFrODvW3nYxf_fmsQ-c-w
